spring:
  datasource:
    master:
      hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://120.76.53.44:3306/aggr?useUnicode=true&characterEncoding=UTF-8
      username: aggr_test
      password: 5i5gT2z1sACZiREpmno3
      connection-timeout: 3000
      maximum-pool-size: 4        # 提升最大连接数
      minimum-idle: 1              # 降低最小空闲连接
      max-lifetime: 840000         # 14分钟
      idle-timeout: 300000         # 5分钟
      keepalive-time: 45000        # 45秒保活
      pool-name: masterHikariPool
      connection-test-query: /* ping */ SELECT 1
      initialization-fail-timeout: 1
      leak-detection-threshold: 60000
    slave:
      hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://120.76.53.44:3306/aggr?useUnicode=true&characterEncoding=UTF-8
      username: aggr_test
      password: 5i5gT2z1sACZiREpmno3
      connection-timeout: 3000
      maximum-pool-size: 4        # 提升最大连接数
      minimum-idle: 1              # 降低最小空闲连接
      max-lifetime: 840000         # 14分钟
      idle-timeout: 300000         # 5分钟
      keepalive-time: 45000        # 45秒保活
      pool-name: slaveHikariPool
      connection-test-query: /* ping */ SELECT 1
      initialization-fail-timeout: 1
      leak-detection-threshold: 60000


logging:
  level:
    ai.yipay: debug
    # 开启泄漏检测日志
#    com.zaxxer.hikari: DEBUG

scheduling:
  enable: false

tg-bot:
  enable: false
  username: YiPayAiLocalBot
  token: 7619414081:AAFmNLzRqzKiE-mkYj64DCnovoaQ8XnqeD8

yipay:
  name: yipay-local
  order-host:
    in: http://127.0.0.1:10001
    id: http://127.0.0.1:10001
    th: http://127.0.0.1:10001
    vn: http://127.0.0.1:10001
    ph: http://127.0.0.1:10001

r2:
  token: H8KyQCYD0E6XSkRZdC_Xokb2n8OLvDiicjBgOXmS
  accessKey: 367515c35d261a50215834674516ba5b
  secretKey: 797b2187ba5657efb208eae078858de6414cae8565b9b64166dfb549f5fbdbe7
  bucketName: yipay
  region: APAC
  endpoint: https://4fddfe2620410d43afcf3bbe5e310c77.r2.cloudflarestorage.com
  downloadUrl: https://r2.yipay.ai