spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://120.76.53.44:3306/aggr?useUnicode=true&characterEncoding=UTF-8
      username: aggr_test
      password: 5i5gT2z1sACZiREpmno3
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: master
      hikari:
        maximum-pool-size: 10
        idle-timeout: 30000
    slave:
      jdbc-url: jdbc:mysql://120.76.53.44:3306/aggr?useUnicode=true&characterEncoding=UTF-8
      username: aggr_test
      password: 5i5gT2z1sACZiREpmno3
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: slave
      hikari:
        maximum-pool-size: 10
        idle-timeout: 30000

logging:
  level:
    # 开启SQL日志
    org.example: DEBUG
    # 开启泄漏检测日志
#    com.zaxxer.hikari: DEBUG

scheduling:
  enable: false

tg-bot:
  enable: false
  username: YiPayAiLocalBot
  token: 7619414081:AAFmNLzRqzKiE-mkYj64DCnovoaQ8XnqeD8

yipay:
  name: yipay-local
  order-host:
    in: http://127.0.0.1:10001
    id: http://127.0.0.1:10001
    th: http://127.0.0.1:10001
    vn: http://127.0.0.1:10001
    ph: http://127.0.0.1:10001

r2:
  token: H8KyQCYD0E6XSkRZdC_Xokb2n8OLvDiicjBgOXmS
  accessKey: 367515c35d261a50215834674516ba5b
  secretKey: 797b2187ba5657efb208eae078858de6414cae8565b9b64166dfb549f5fbdbe7
  bucketName: yipay
  region: APAC
  endpoint: https://4fddfe2620410d43afcf3bbe5e310c77.r2.cloudflarestorage.com
  downloadUrl: https://r2.yipay.ai

# 系统配置
system:
  captcha-enable: true